SET TERM !!;

CREATE PROCEDURE GET_APARATOS (
    MES INTEGER,
    ANIO INTEGER)
RETURNS (
    NOMBRE VARCHAR (101) CHARACTER SET NONE,
    DISIPLINA VARCHAR (50) CHARACTER SET NONE,
    TOTAL DECIMAL (8, 3))
AS
declare variable DIS INTEGER;
declare variable CLI INTEGER;
declare variable CLASE DECIMAL(8,3);
declare variable TOTAL_AUX DECIMAL(8,3);
BEGIN
  TOTAL = 0;
  FOR SELECT DISIPLINA, CLIENTE FROM APARATOS WHERE PAGA='S' AND FECHA_INGRESO LIKE '%'||(CAST(:MES AS VARCHAR(2)))||'/'||(CAST (:ANIO AS VARCHAR(4)))
      INTO :DIS, :CLI
  DO
  BEGIN
       IF (NOT EXISTS(SELECT P.ID_DISIPLINA FROM PRACTICA P, DISIPLINAS D WHERE (P.ID_CLIENTE=:CLI AND
           P.ID_DISIPLINA=D.ID_DISIPLINA AND D.NOMBRE = 'Pase Libre'))) THEN
       BEGIN
            SELECT NOMBRE||' '||APELLIDO FROM CLIENTES WHERE (ID_CLIENTE=:CLI) INTO :NOMBRE;
            SELECT NOMBRE, PRECIO_CLASE FROM DISIPLINAS WHERE ID_DISIPLINA=:DIS INTO :DISIPLINA,:CLASE;
            TOTAL_AUX = TOTAL_AUX+(CLASE-5);
            SUSPEND;
       END
  END
  TOTAL = TOTAL_AUX;
  SUSPEND;
END!!

SET TERM ;!!

