SET TERM !!;

CREATE PROCEDURE GET_AEROBICOS (
    MES INTEGER,
    ANIO INTEGER)
RETURNS (
    PROFESOR VARCHAR (101) CHARACTER SET NONE,
    DISIPLINA VARCHAR (50) CHARACTER SET NONE,
    CANT_CLASES INTEGER,
    SUELDO_MENSUAL DECIMAL (8, 3))
AS
declare variable FECHA_AUX DATE;
declare variable CANT INTEGER;
declare variable DIS INTEGER;
declare variable PROFE INTEGER;
declare variable SUELDO DECIMAL(8,3);
declare variable TS VARCHAR(1);
declare variable CANT_AUX INTEGER;
declare variable PRECIO_CLASE DECIMAL(8,3);
declare variable F VARCHAR(10);
BEGIN
  CANT_CLASES = 0;
  
  FOR SELECT DISTINCT(ID_PERSONAL) FROM ACARGO WHERE ANIO=:ANIO AND MES=:MES INTO :PROFE
  DO
    BEGIN
      SELECT NOMBRE||' '||APELLIDO, SUELDO, TIPO_SUELDO FROM PERSONAL WHERE ID_PERSONAL=:PROFE
      INTO :PROFESOR, :SUELDO, :TS;
      FOR SELECT DISTINCT(ID_DISIPLINA) FROM ACARGO WHERE (ANIO=:ANIO AND MES=:MES) AND (ID_PERSONAL=:PROFE)
          INTO :DIS
      DO
      BEGIN
           SELECT COUNT(ID_DISIPLINA) FROM ACARGO WHERE (MES=:MES AND ANIO=:ANIO)
           AND (ID_PERSONAL=:PROFE) AND (ID_DISIPLINA=:DIS) INTO :CANT;
           SELECT NOMBRE, PRECIO_CLASE FROM DISIPLINAS WHERE ID_DISIPLINA=:DIS INTO :DISIPLINA, :PRECIO_CLASE;
           CANT_CLASES = CANT*4;
           IF (TS='C') THEN
                SUELDO_MENSUAL = CAST (CANT_CLASES AS DECIMAL(8,3))*SUELDO;
           ELSE
               BEGIN
                    F = '%'||CAST(:MES AS VARCHAR(2))||'/'||CAST(:ANIO AS VARCHAR(4));
                    SELECT COUNT(NUMERO) FROM NUMEROS WHERE FECHA LIKE :F AND DISIPLINA=:DIS
                    INTO :CANT_AUX;
                    SUELDO_MENSUAL = (CANT_AUX*PRECIO_CLASE)*(SUELDO/100);
               END
           SUSPEND;
      END
    END
END !!

SET TERM ;!!


