CREATE GENERATOR "GEN_ID_ESTABLECIMIENTO";
SET GENERATOR "GEN_ID_ESTABLECIMIENTO" TO 1;

CREATE GENERATOR "GEN_ID_ARTICULO";
SET GENERATOR "GEN_ID_ARTICULO" TO 1;

CREATE GENERATOR "GEN_ID_CLIENTE";
SET GENERATOR "GEN_ID_CLIENTE" TO 1;

CREATE GENERATOR "GEN_ID_DISIPLINA";
SET GENERATOR "GEN_ID_DISIPLINA" TO 1;

CREATE GENERATOR "GEN_ID_ENFERMEDAD";
SET GENERATOR "GEN_ID_ENFERMEDAD" TO 1;

CREATE GENERATOR "GEN_ID_PERSONAL";
SET GENERATOR "GEN_ID_PERSONAL" TO 1;

CREATE GENERATOR "GEN_ID_ROL";
SET GENERATOR "GEN_ID_ROL" TO 1;

CREATE GENERATOR "GEN_ID_USUARIO";
SET GENERATOR "GEN_ID_USUARIO" TO 1;