CREATE TABLE TIENEENFERMEDAD(
       ID_ENFERMEDAD INTEGER NOT NULL,
       ID_CLIENTE INTEGER NOT NULL
);

ALTER TABLE TIENEENFERMEDAD ADD CONSTRAINT PK_TIENEENFERMEDAD PRIMARY KEY(ID_ENFERMEDAD,ID_CLIENTE);
ALTER TABLE TIENEENFERMEDAD ADD CONSTRAINT FK_TIENEENFERMEDAD_ENFERMEDAD FOREIGN KEY(ID_ENFERMEDAD) REFERENCES ENFERMEDADES(ID_ENFERMEDAD);
ALTER TABLE TIENEENFERMEDAD ADD CONSTRAINT FK_TIENEENFERMEDAD_CLIENTES FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);
