CREATE TABLE STOCK(
       ID_ARTICULO INTEGER NOT NULL,
       ESTABLECIMIENTO INTEGER NOT NULL,
       CANTIDAD INTEGER
);

ALTER TABLE STOCK ADD CONSTRAINT PK_STOCK PRIMARY KEY(ID_ARTICULO,ESTABLECIMIENTO);
ALTER TABLE STOCK ADD CONSTRAINT FK_STOCK_ARTICULOS FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULOS(ID_ARTICULO);
ALTER TABLE STOCK ADD CONSTRAINT FK_STOCK_ESTABLECIMIENTO FOREIGN KEY(ESTABLECIMIENTO) REFERENCES ESTABLECIMIENTO(ID_ESTABLECIMIENTO);
