CREATE TABLE USUARIOS(
       ID_USUARIO INTEGER NOT NULL,
       NOMBRE VARCHAR(10),
       PASS VARCHAR(10),
       ID_ROL INTEGER,
       ID_PERSONAL INTEGER,
       ESTABLECIMIENTO INTEGER
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY(ID_USUARIO);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_ROL_USUARIOS FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_PERSONAL_USUARIOS FOREIGN KEY(ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_ESTABLECIMIENTO_USUARIOS FOREIGN KEY(ESTABLECIMIENTO) REFERENCES ESTABLECIMIENTO(ID_ESTABLECIMIENTO);
ALTER TABLE PERSONAL ADD CONSTRAINT FK_USUARIOS_PERSONAL FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
