CREATE TABLE ESTABLECIMIENTO(
       ID_ESTABLECIMIENTO INTEGER NOT NULL,
       NOMBRE VARCHAR(50),
       DIRECCION VARCHAR(50),
       TELEFONO INTEGER
);

ALTER TABLE ESTABLECIMIENTO ADD CONSTRAINT PK_ESTABLECIMIENTO PRIMARY KEY(ID_ESTABLECIMIENTO);