CREATE TABLE RESERVAS(
       ID_CLIENTE INTEGER NOT NULL,
       ID_DISIPLINA INTEGER NOT NULL,
       FECHA_RESERVACION DATE NOT NULL,
       IMPORTE FLOAT,
       PAGO VARCHAR(1),
       FECHA_RESERVA DATE,
       CANTIDAD INTEGER
);

ALTER TABLE RESERVAS ADD CONSTRAINT PK_RESERVAS PRIMARY KEY(ID_CLIENTE,ID_DISIPLINA,FECHA_RESERVACION);
ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);
ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_DISIPLINA FOREIGN KEY(ID_DISIPLINA) REFERENCES DISIPLINAS(ID_DISIPLINA);
