CREATE TABLE PERSONAL(
       ID_PERSONAL INTEGER NOT NULL,
       NOMBRE VARCHAR(50),
       APELLIDO VARCHAR(50),
       EDAD INTEGER,
       DNI INTEGER,
       SUELDO DECIMAL(8,3),
       ID_USUARIO INTEGER,
       ESTABLECIMIENTO INTEGER
);

ALTER TABLE PERSONAL ADD CONSTRAINT PK_PERSONAL PRIMARY KEY(ID_PERSONAL);
ALTER TABLE PERSONAL ADD CONSTRAINT FK_ESTABLECIMIENTO_PERSONAL FOREIGN KEY(ESTABLECIMIENTO) REFERENCES ESTABLECIMIENTO(ID_ESTABLECIMIENTO);

