SET TERM !!;
CREATE TRIGGER INSERT_ESTABLECIMIENTO FOR ESTABLECIMIENTO
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_ESTABLECIMIENTO = GEN_ID (GEN_ID_ESTABLECIMIENTO, 1);
END!!
SET TERM ;!!

SET TERM !!;
CREATE TRIGGER INSERT_ARTICULOS FOR ARTICULOS
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_ARTICULO = GEN_ID (GEN_ID_ARTICULO, 1);
END!!
SET TERM ;!!

SET TERM !!;
CREATE TRIGGER INSERT_CLIENTES FOR CLIENTES
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_CLIENTE = GEN_ID (GEN_ID_CLIENTE, 1);
END!!
SET TERM ;!!

SET TERM !!;
CREATE TRIGGER INSERT_DISIPLINA FOR DISIPLINAS
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_DISIPLINA = GEN_ID (GEN_ID_DISIPLINA, 1);
END!!
SET TERM ;!!

SET TERM !!;
CREATE TRIGGER INSERT_ENFERMEDAD FOR ENFERMEDADES
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_ENFERMEDAD = GEN_ID (GEN_ID_ENFERMEDAD, 1);
END!!
SET TERM ;!!

SET TERM !!;
CREATE TRIGGER INSERT_PERSONAL FOR PERSONAL
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_PERSONAL = GEN_ID (GEN_ID_PERSONAL, 1);
END!!
SET TERM ;!!

SET TERM !!;
CREATE TRIGGER INSERT_USUARIO FOR USUARIOS
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_USUARIO = GEN_ID (GEN_ID_USUARIO, 1);
END!!
SET TERM ;!!

SET TERM !!;
CREATE TRIGGER INSERT_ROL FOR ROLES
BEFORE INSERT
POSITION 0
AS BEGIN
	NEW.ID_ROL = GEN_ID (GEN_ID_ROL, 1);
END!!
SET TERM ;!!