CREATE TABLE CROSSFIT (
  DISCIPLINA INTEGER,
  ID_CLIENTE INTEGER,
  FECHA DATE,
  HORA TIME,
  PAGA VARCHAR(1));

ALTER TABLE CROSSFIT ADD CONSTRAINT FK_CROSSFIT FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);

CREATE TABLE PAGO_CROSSFIT (
  CLIENTE INTEGER,
  FECHA_PAGO DATE,
  FECHA_EFECTIVO DATE,
  DISCIPLINA INTEGER);



  insert into Aparatos values (:disiplina,:cliente,:hora,'N',:fecha)


