CREATE TABLE PARAMETROS(
       ID_PARAMETRO INTEGER NOT NULL,
       DESCRIPCION VARCHAR(50),
       VALOR INTEGER
);

ALTER TABLE PARAMETROS ADD CONSTRAINT PK_PARAMETROS PRIMARY KEY(ID_PARAMETRO);

INSERT INTO PARAMETROS VALUES(1,'DESCUENTO APARATOS',5);
INSERT INTO PARAMETROS VALUES(2,'PORSENTAJE PASE LIBRE',30);
INSERT INTO PARAMETROS VALUES(3,'AVISO CUMPLE INICIO',1);